version: '3.5'

services:
  frontend:
    image: frontend
    #ports: 
    #  - 5000:5000
    environment:
      - API_URL=http://localhost/api
    container_name: frontend

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis-db
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PASSWORD=postgres
      - FRONT_URL=http://localhost
    depends_on:
      - redis-db
      - postgres-db
    container_name: backend
        
  redis-db:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA= ./database
    volumes:
      - database:/database
    restart: unless-stopped
    container_name: postgres-db
  
  nginx-proxy:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
    depends_on:
      - frontend
      - backend

volumes:
  database:
